### ISSUE TITLE
Functional Tests with Selenium Server and RC dont work with VPU

### ISSUE THREAD

**Issue by LVier** [NSinopoli/VisualPHPUnit#103]
Hello,

I am using:
- php5.3.13
- selenium-server-standalone-2.33.0

And I am able to do my functional test cases by console with "phpunit".
But when I try it with VPU, I get this error at browser:

testIndex
Invalid response while accessing the Selenium Server at 'http://localhost:4444/selenium-server/driver/': Failed to start new browser session: java.lang.RuntimeException: Browser not supported: (Did you forget to add a *?) Supported browsers include: *firefox *mock *firefoxproxy *pifirefox *chrome *iexploreproxy *iexplore *firefox3 *safariproxy *googlechrome *konqueror *firefox2 *safari *piiexplore *firefoxchrome *opera *webdriver *iehta *custom
Execution time: 0.10344195365906s
Stack Trace:
Array
(
    [0] => Array
        (
            [file] => C:\wamp\www\yii\framework\test\CWebTestCase.php
            [line] => 63
            [function] => __call
            [class] => PHPUnit_Extensions_SeleniumTestCase
            [type] => ->
            [args] => Array
                (
                    [0] => start
                    [1] => Array
                        (
                        )

                )

        )

    [1] => Array
        (
            [file] => C:\wamp\www\protected\tests\WebTestCase.php
            [line] => 24
            [function] => prepareTestSession
            [class] => PHPUnit_Extensions_SeleniumTestCase
            [type] => ->
            [args] => Array
                (
                )

        )

)

In the selenium server console I receive this:

15:01:31.798 INFO - Command request: getNewBrowserSession[, http://localhost/testdrive/index-test.php/] on session null
15:01:31.799 INFO - creating new remote session
15:01:31.801 INFO - Got result: Failed to start new browser session: java.lang.RuntimeException: Browser not supported:
(Did you forget to add a *?)

Supported browsers include:
  *firefox
  *mock
  *firefoxproxy
  *pifirefox
  *chrome
  *iexploreproxy
  *iexplore
  *firefox3
  *safariproxy
  *googlechrome
  *konqueror
  *firefox2
  *safari
  *piiexplore
  *firefoxchrome
  *opera
  *webdriver
  *iehta
  *custom
 on session null

It looks like VPU starts a browser session with phpunit but without a specific browser.
Even though I have configurated the array in the bootstrap.php:

 // In order for VPU to function correctly, the configuration files must
 // contain a JSON listener (see the README for more information)
    'xml_configuration_files' => array(
       "{$root}/app/config/phpunit.xml",
	   "../../../protected/tests/phpunit.xml",  // <-- this is the .xml file which phpunit uses when running in console but VPU doesnt
    ),

So what might be the reason that it works perfectly by running phpunit in console and that it wont work with VPU?

Thanks in advance!

Kind regards

**Comment by localgod** [comment]
This is is very old and I plan to revamp a lot of things in the project so I'm gonna clode this one.
