### ISSUE TITLE
No files to test when offline

### ISSUE THREAD

**Issue by samuelmolinski** [NSinopoli/VisualPHPUnit#77]
i was working with your amazing tool here and lost connection to the internet.  During that time I refreshed the page and 'lost' the files show my various test (including your sample test).  The files remained missing until i had Internet again.  Is this normal? Is there an outside dependency or something preventing me from using it completely offline?

**Comment by localgod** [comment]
This is is very old and I plan to revamp a lot of things in the project so I'm gonna clode this one.
