### ISSUE TITLE
Fatal error not shown

### ISSUE THREAD

**Issue by sylfabre** [NSinopoli/VisualPHPUnit#91]
Hi!

First thank you for this awesome tool :-)

I've been searching for a while why some of my tests returned a blank screen : if a fatal error is thrown during the testing them the POST request response is empty (fatal error like Allowed memory exhausted).

I've been able to find the error commenting ob_start() in app/lib/VPU.php at line 438.

I don't know if this is a bug of PHP not displaying buffer content after fatal error or something related to this post : http://www.php.net/manual/fr/function.ob-start.php#108016

**Comment by localgod** [comment]
This is is very old and I plan to revamp a lot of things in the project so I'm gonna clode this one.
