### ISSUE TITLE
New Project Maintainer

### ISSUE THREAD

**Issue by NSinopoli** [NSinopoli/VisualPHPUnit#94]
Really hate to do this, but to avoid complete bit rot, I think it's best if I step aside as the maintainer and open up the floor for someone else to take the lead. I haven't used PHP in any serious capacity in quite some time, and I don't see that changing any time soon.

However, it's not my intention to just dump the project on someone else. I still have a fair amount of uncommitted code that applies to at least one issue (https://github.com/NSinopoli/VisualPHPUnit/issues/81), and I'll be more than happy to assist in whatever way I can to make the whole transition process as smooth as possible. 

Going forward, I would love for VPU to be incorporated upstream as part of the PHPUnit project (@sebastianbergmann, @edorian - any chance of this happening?), but barring that, I could create a GitHub organization and then grant the appropriate project permissions there.

Please let me know if you're interested in being the new maintainer of VPU.

**Comment by localgod** [comment]
I would like to give it a go as project maintainer. All my current projects are using the MIT license, so I would like to use that license.

**Comment by NSinopoli** [comment]
@localgod, thanks for your interest! I've added you as a collaborator.

Please leave the BSD license intact. Minus the promotion clause, it's essentially identical to the MIT license.

**Comment by localgod** [comment]
@NSinopoli could you transfer the project to me. It seem I'm not allowed to used services like scrutinizer-ci.com and travis-ci.com if I'm not the owner.

**Comment by NSinopoli** [comment]
@localgod I created an organization and added you as an owner.
